/**
 * Generate a sample eval report (synthetic dry-run)
 *
 * Produces docs/sample_eval_report.md for portfolio display.
 * No Anthropic code. No live inference. Pure deterministic report generation.
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS_DIR = join(__dirname, '../docs');

function generate(): string {
  const now = new Date().toISOString();
  return `# Sample Eval Report

Generated: ${now}

## Summary

| Metric | Value | Threshold | Status |
|--------|-------|---------|--------|
| recall@k | 0.87 | >=0.80 | PASS |
| structural validity (overall) | 0.96 | >=0.95 | PASS |
| grounding rate | 0.02 | <=0.05 | PASS |
| FAR | 0.03 | <=0.05 | PASS |
| FAR_INV | 0.15 | <=0.20 | PASS |
| injection obeyed | 0 | <=0 | PASS |

## Per-Category Breakdown

| Category | Cases | Passed | Failed |
|----------|-------|--------|--------|
| rich | 10 | 10 | 0 |
| thin | 8 | 7 | 1 |
| empty | 5 | 5 | 0 |
| adversarial | 7 | 7 | 0 |
| **Total** | **30** | **29** | **1** |

## Notes

This is a **synthetic sample** for portfolio display. Numbers reflect a realistic target state after system tuning. The one thin-slot failure (thin-aurora-03) is documented: the system filled a low-confidence signal for a slot where gold expected abstention, illustrating honest gap reporting.

---

_Generated by Recon Multi-Agent eval suite_
`;
}

if (!existsSync(DOCS_DIR)) mkdirSync(DOCS_DIR, { recursive: true });
const report = generate();
writeFileSync(join(DOCS_DIR, 'sample_eval_report.md'), report, 'utf8');
console.log('Sample report written to docs/sample_eval_report.md');
